### ISSUE TITLE
Support for Kubic/Cri-o

### ISSUE THREAD

**Issue by anthr76** [openSUSE/microos-toolbox#30]
Is podman required on the Kubic variant? Would it be possible to have compatibility with crictl? As I understand it this would likely require a ton of modifications to the script. Is it advised to install podman on top of kubic?

**Comment by thkukuk** [comment]
podman is required for toolbox. No idea if this all works with crictl, somebody needs to check.
But as long as you don't install the podman cni config, podman works fine on top of Kubic.

**Comment by thkukuk** [comment]
crictl is not used anymore and Kubic doesn't exist anymore.
